export type Gender = "male" | "female" | "non-binary" | "prefer-not-to-say";

export interface PartnerInfo {
  name: string;
  birthday: string;
  gender: Gender | "";
}

export type AnswerValue = string | [string, string];

/** Everything the paid pass needs to replay the test. */
export interface TranscriptData {
  partner1: PartnerInfo;
  partner2: PartnerInfo;
  relationshipStart: string;
  answers: Record<string, AnswerValue>;
}

export interface TestStore {
  partner1: PartnerInfo;
  partner2: PartnerInfo;
  relationshipStart: string;
  email: string;
  answers: Record<string, AnswerValue>;
  reportId: string | null;
  teaser: FreeReport | null;
  setPartner1: (data: Partial<PartnerInfo>) => void;
  setPartner2: (data: Partial<PartnerInfo>) => void;
  setRelationshipStart: (date: string) => void;
  setEmail: (email: string) => void;
  setAnswer: (questionId: string, answer: AnswerValue) => void;
  setReport: (reportId: string, teaser: FreeReport) => void;
  resetTest: () => void;
}

/** The five scored dimensions. Order here drives the order in the UI. */
export const CATEGORY_IDS = [
  "communication",
  "conflict",
  "trust",
  "intimacy",
  "values",
] as const;

export type CategoryId = (typeof CATEGORY_IDS)[number];

export const CATEGORY_LABELS: Record<CategoryId, string> = {
  communication: "Communication",
  conflict: "Conflict Resolution",
  trust: "Trust & Boundaries",
  intimacy: "Emotional Intimacy",
  values: "Shared Values & Goals",
};

export interface CategoryScore {
  id: CategoryId;
  name: string;
  score: number;
  /** One sentence — this is the free hook. */
  headline: string;
}

/* ------------------------------- free tier -------------------------------- */

/** The relationship archetype, named and justified. */
export interface HiddenDynamic {
  /** e.g. "The Pursuer & Withdrawer", "The Anchor & Kite". */
  type: string;
  description: string;
}

/** Generated by Haiku the moment the test is submitted. */
export interface FreeReport {
  overallScore: number;
  verdict: string;
  hiddenDynamic: HiddenDynamic;
  categories: CategoryScore[];
  /** One line summarising the blitz round. */
  flagSummary: string;
}

/* ------------------------------- paid tier -------------------------------- */

export interface BiggestSurprise {
  /** One finding that breaks an assumption — not "you are different". */
  insight: string;
}

export interface SeeEachOther {
  partner1View: string;
  partner2View: string;
  /** What the contrast (or similarity) says about the relationship. */
  dynamic: string;
}

export interface BiggestMisunderstanding {
  partner1Thinks: string;
  partner2Experiences: string;
}

export interface ConflictDNA {
  pattern: string;
  trigger: string;
  escalation: string;
  aftermath: string;
  insight: string;
}

export interface HowYouLove {
  partner1: string;
  partner2: string;
  friction: string;
}

export interface IfNothingChanges {
  prediction: string;
  why: string;
}

export interface WhatKeepsYouTogether {
  core: string;
  evidence: string;
}

export interface BiggestQuestion {
  question: string;
  conversationStarters: string[];
}

/** Generated by Sonnet after payment, in a single request. */
export interface PaidReport {
  biggestSurprise: BiggestSurprise;
  seeEachOther: SeeEachOther;
  biggestMisunderstanding: BiggestMisunderstanding;
  conflictDNA: ConflictDNA;
  howYouLove: HowYouLove;
  ifNothingChanges: IfNothingChanges;
  whatKeepsYouTogether: WhatKeepsYouTogether;
  biggestQuestion: BiggestQuestion;
}

/* -------------------------------- storage --------------------------------- */

/**
 * `unpaid`     — default; the deep analysis has not been requested.
 * `processing` — payment confirmed, Sonnet is generating.
 * `ready`      — the paid sections are stored.
 */
export type PaidStatus = "unpaid" | "processing" | "ready";

export interface StoredReport {
  id: string;
  createdAt: number;
  email: string;
  partner1Name: string;
  partner2Name: string;
  /** Kept so the paid pass can replay the test without the client. */
  answers: TranscriptData;
  free: FreeReport;
  paid: PaidReport | null;
  paidStatus: PaidStatus;
}
